Homework04
kovalchykigor/work_2 pull request #2
Opened 2024-06-01 16:53 UTC by kovalchykigor

2024-06-04 16:13 UTC, MrCrow79 requested changes

2024-06-04 16:13 UTC, MrCrow79 commented on lesson_04/homework_04.py
> +##  ПЕРЕЗАПИСУЙТЕ зміст змінної adwentures_of_tom_sawer у завданнях 1-3
Зверни увагу на слово перезаписуйте значення змінної. Ти цього не зробив в задачах  1-3

2024-06-04 16:13 UTC, MrCrow79 commented on lesson_04/homework_04.py
> +        count += 1
Гарно

2024-06-04 16:13 UTC, MrCrow79 commented on lesson_04/homework_04.py
> +print("The letter 'h' is found in the text ", result_04, " times", "\n")
можна було 
print("The letter 'h' is found in the text ", result_03.count('h'), " times", "\n")

2024-06-04 16:13 UTC, MrCrow79 commented on lesson_04/homework_04.py
> +second_find = result_03.find("Tom", first_find + 1)
Так, вірний підхід :)
можна навітьбуло зробити красивіше:
`result_03.find("Tom", result_03.find("Tom") + 1)`

2024-06-04 16:13 UTC, MrCrow79 commented on lesson_04/homework_04.py
> +result = len(adwentures_of_tom_sawer_sentences[4].split())
ти число 4 порахував очами, а не за допомогою  python, тому не рахуеться

2024-06-04 16:13 UTC, MrCrow79 commented on lesson_04/homework_04.py
> +for sentenсe in adwentures_of_tom_sawer_sentences:
тут `c ` в слові sentence кирилічна, а не латинська :)

2024-06-04 16:13 UTC, MrCrow79 commented on lesson_04/homework_04.py
> +print(adwentures_of_tom_sawer_sentences[4].lower(), "\n")
ти вівів п'яте речення

2024-06-05 21:04 UTC, kovalchykigor commented on lesson_04/homework_04.py
> +for sentenсe in adwentures_of_tom_sawer_sentences:
ппц, і всеодно програма компілюється! это вам не турбо паскаль

2024-06-11 09:01 UTC, closed without merging