home work 27.1 is done
kovalchykigor/work_2 pull request #22
Opened 2024-08-31 16:09 UTC by kovalchykigor

2024-09-02 06:43 UTC, MrCrow79 requested changes

2024-09-02 06:43 UTC, MrCrow79 commented on lesson_27/__init__.py
> +    url = "https://tracking.novaposhta.ua/#/uk"
або можна було б винести в constants. Не принципово

2024-09-02 06:43 UTC, MrCrow79 commented on lesson_27/test_parсel_status.py
> +                                 pytest.param(ParcelCode.parcel_code, "Отримано")
ТОді радив би всі коди вонисити в одне місцу, наприклад


class ParcelCodes:
    with_status_in_progress = "20450986085676"
    with_status_delivered = "..."
    
     invalid= "1111111111111111"

2024-09-02 06:43 UTC, MrCrow79 commented on lesson_27/test_parсel_status.py
> +    assert expected_message in parcel_status.text, f"NO '{expected_message}' in received message"
Ну а тут нема класу Сторінки з методами пошуку і отримання меседжа, тому це не зараховано

2024-09-05 15:42 UTC, kovalchykigor commented on lesson_27/test_parсel_status.py
> +                                 pytest.param(ParcelCode.parcel_code, "Отримано")
А як потім додвати їх з класу в параметри тесту?

2024-09-05 16:00 UTC, MrCrow79 commented on lesson_27/test_parсel_status.py
> +                                 pytest.param(ParcelCode.parcel_code, "Отримано")
Невірно сформулювавю Звісно в цей клас додасти не видйю
є такі 2 варіанти(варіантів більше, це як приклад):

```
import pytest

const_param_1 = 'const_param_1'
const_param_2 = 'const_param_2'

class SometestPositiveCases():

    param_1 = 'param_1'
    param_2 = 'param_2'

    def get_cases(self):
        return [self.param_2, self.param_2]


class TestSome:

    @pytest.mark.parametrize('param', SometestPositiveCases().get_cases())
    def test_first_test_extra_class(self, param):
        print(param)

    @pytest.mark.parametrize('param', [const_param_1, const_param_2])
    def test_first_test_constants(self, param):
        print(param)
```

2024-09-05 16:02 UTC, MrCrow79 commented on lesson_27/test_parсel_status.py
> +        )
можно винести в BasePage як get_text

2024-09-05 16:07 UTC, MrCrow79 commented on lesson_27/test_parсel_status.py
> +        super().__init__(driver=driver, url=url)
url нащо присилати - він же статичний повинен бути

2024-09-05 16:09 UTC, MrCrow79 commented on lesson_27/test_parсel_status.py
> +        np_search_page.button_click(By.CSS_SELECTOR, Locators.pop_up_button)
незгоден, тобі в тесті непотрібно вказувати локатори і тд, це все деталі реалізації.
краще ці дії пенести в клас сторінки

```

class NPSearchPage(BasePage)
    ...
    def input_parsel_number(number):
         self.send_keys(By.ID, Locators.input_field, number) 
        return self
    def click_find():
        ....
    

@fixture
def np_search_page(driver):
        np_search_page = NPSearchPage(driver)
        np_search_page.open()
        return np_search_page 

 def test_np(self, np_search_page, parcel_number, expected_message):
    np_search_page.input_parsel_number(parcel_number)
    np_search_page.click_find()
    ....
```

А якщо все робити зовсім правильно, то на сторінці  NPSearchPage буде метод find_parsel який все це буде робити і тоді при зміні алгоритму пошуку. ти будеш міняти тільки в одному місці це, а не по всім тестам

2024-09-05 16:10 UTC, MrCrow79 approved these changes

2024-09-05 17:24 UTC, kovalchykigor commented on lesson_27/test_parсel_status.py
> +        )
Тоді в класі NPSearchPage жодного методу не залишиться

2024-09-05 18:16 UTC, kovalchykigor commented on lesson_27/test_parсel_status.py
> +        np_search_page.button_click(By.CSS_SELECTOR, Locators.pop_up_button)
Для чого return self робиться?
Було б добре як би додавав коментарі до твоїх прикладів коду, ооп стиль не так швидко влягається в моїй голові)

2024-09-06 14:34 UTC, closed without merging